config/routes.rb
Rails.application.routes.draw do
	get 'pages/home'
  get 'pages/about'
  get 'pages/help'
  get 'home', to: 'pages#home'
  get 'help', to: 'pages#help'
  get 'about', to: 'pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'application#hello'
  root 'pages#home'

  resources :users
  # 用户注册
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  # 用户登录
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # 用户激活
  resources :account_activations, only: [:edit]

  # 密码重设
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	before_action :get_user, only: [:edit, :update]
	before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]
  def new
  end
  def create
  	@user = User.find_by(email: params[:password_reset][:email].downcase)
  	if @user
  		@user.create_reset_digest
  		@user.send_password_reset_email
  		flash[:info] = "Please check your email"
  		redirect_to root_url
  	else
  		flash.now[:danger] = "No such email"
  		render :new
  	end
  end

  def edit
  end
  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render :edit
    elsif @user.update_attributes(user_params)
      login @user
      flash[:success] = "Password has been reset."
      redirect_to @user
    else
      render :edit
    end
  end


  private
  	def get_user
  		@user = User.find_by(email: params[:email])
  	end
  	def valid_user
  		unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
  			redirect_to root_url
  		end
  	end
    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end
    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.haml
- provide :title, "Reset Password"

.row
	.col-md-4.col-md-offset-4
		.panel.panel-default
			.panel-body
				= simple_form_for @user, url: password_reset_url(params[:id]) do |f|
					= hidden_field_tag :email, @user.email
					= f.input :password
					= f.input :password_confirmation
					= f.submit "Submit", class: "btn btn-primary"

app/views/password_resets/new.html.haml
- provide :title, "Password Reset"

.row
	.col-md-4.col-md-offset-4
		.panel.panel-default
			.panel-body
				= simple_form_for :password_reset, url: password_resets_url do |f|
					= f.input :email
					= f.button "submit", class: "btn btn-primary"