config/routes.rb
Rails.application.routes.draw do
	get 'pages/home'
  get 'pages/about'
  get 'pages/help'
  get 'home', to: 'pages#home'
  get 'help', to: 'pages#help'
  get 'about', to: 'pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'application#hello'
  root 'pages#home'

  resources :users
  # 用户注册
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  # 用户登录
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # 用户激活
  resources :account_activations, only: [:edit]

  # 密码重设
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token, :activation_token, :reset_token
	before_save :email_downcase
	before_create :create_activation_digest
	validates :name, presence: true, length: { in: 3..50 }
	# email 的唯一性验证并不能做到数据库中的唯一
	# 为此需要为数据库的 email 列添加索引，并为索引添加唯一性验证
	# rails g migration add_index_to_users_email
	# add_index :users, :email, unique: true
	validates :email, presence: true, length: { maximum: 255 }, email_format: { message: "is not looking good." }, 
										uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 6 }, presence: true, allow_nil: true
	has_secure_password

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end
	def forget
		update_attribute(:remember_digest, nil)
	end
	def activate
		# update_attribute(:activated, true)
		# update_attribute(:activated_at, Time.zone.now)
		update_columns(activated: true, activated_at: Time.zone.now)
	end
	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end
	def authenticated?(attribute, token)
		digest = send("#{attribute}_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end
	def create_reset_digest
		self.reset_token = User.new_token
		update_attribute(:reset_digest, User.digest(reset_token))
		update_attribute(:reset_sent_at, Time.zone.now)
	end
	def send_password_reset_email
		UserMailer.password_reset(self).deliver_now
	end
	def password_reset_expired?
		reset_sent_at < 2.hours.ago
	end

	# 为 users.yml 中的测试数据库中的用户生成密码
	def User.digest string
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
																									BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
	def User.new_token
		SecureRandom.urlsafe_base64
	end
	private
		def email_downcase
			self.email.downcase!
		end
		def create_activation_digest
			self.activation_token = User.new_token
			self.activation_digest = User.digest(activation_token)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]
  def index
    @users = User.where(activated: true).paginate(page: params[:page], per_page: 10)
  end
  def new
  	@user = User.new
  end
  def create
  	@user = User.new(user_params)
  	if @user.save
      @user.send_activation_email
  		flash[:info] = "#{@user.id} 请去 #{@user.email} 激活你的账户"
  		redirect_to root_url
  	else
  		render :new
  	end
  end
  def show
  	@user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated?
  end
  def edit
  end
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Update Profile success"
      redirect_to edit_user_url(@user)
    else
      render :edit
    end
  end
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end
    def logged_in_user
      unless logged_in?
        store_location
        flash[:warning] = "Please login before your move"
        redirect_to login_url
      end
    end
    def correct_user
      @user = User.find(params[:id])
      if @user != current_user
        flash[:warning] = "Please dont touch other's info"
        redirect_to root_url
      end
    end
    def admin_user
      redirect_to root_url unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.haml
.list-group-item
	.media
		.media-left
			= gravatar_for(user, size: 46, class: "img-rounded")
		.media-body
			%h4.media-heading
				= link_to user.name, user_url(user)
			= user.email
		.media-right
			- if current_user.admin? && (user != current_user)
				= link_to "DELETE", user_url(user), method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-default'

app/views/users/edit.html.haml
- provide :title, "Update Profile"
.row
	.col-md-8
		.panel.panel-default
			.panel-body
				= simple_form_for @user, defaults: { input_html: { class: "input-sm" } } do |f|
					= f.input :name, placeholder: "USERNAME"
					= f.input :email, placeholder: "EMAIL"
					= f.input :password, placeholder: "PASSWORD"
					= f.input :password_confirmation, placeholder: "CONFIRMATION"
					= f.button :submit, class: "btn-sm btn-primary"

app/views/users/index.html.haml
- provide :title, "All Users"

.row
	.col-md-8
		= will_paginate
		.list-group
			= render @users

app/views/users/new.html.haml
- provide :title, "Sign Up"
.row
	.col-md-4.col-md-offset-8
		.panel.panel-default
			.panel-body
				= simple_form_for @user, url: signup_url, defaults: { label: false, input_html: { class: "input-sm" } } do |f|
					= f.input :name, placeholder: "USERNAME"
					= f.input :email, placeholder: "EMAIL"
					= f.input :password, placeholder: "PASSWORD"
					= f.input :password_confirmation, placeholder: "CONFIRMATION"
					= f.button :submit, class: "btn-sm btn-primary"

#bg
	= image_tag("tokyo.jpg", alt: "background image")

app/views/users/show.html.haml
.row
	.col-md-4
		.panel.panel-default.user-profile-card
			.panel-body
				.media
					.media-left
						= gravatar_for @user, size: 90, class: "img-circle"
					.media-body
						.item.name
							= @user.name
						.item.gray
							第
							= @user.id
							位会员
							\/
							= @user.created_at.localtime.to_s(:db)
				.follow-info.row
					.col-xs-4.followers
						= link_to "12", "#", class: "counter"
						= link_to "关注着", "#", class: "text"
					.col-xs-4.following
						= link_to "70", "#", class: "counter"
						= link_to "正在关注", "#", class: "text"
					.col-xs-4.stars
						= link_to "8", "#", class: "counter"
						= link_to "收藏", "#", class: "text"

	.col-md-8