config/routes.rb
Rails.application.routes.draw do
	get 'pages/home'
  get 'pages/about'
  get 'pages/help'
  get 'home', to: 'pages#home'
  get 'help', to: 'pages#help'
  get 'about', to: 'pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'application#hello'
  root 'pages#home'

  resources :users
  # 用户注册
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  # 用户登录
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # 用户激活
  resources :account_activations, only: [:edit]

  # 密码重设
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/_flash.html.haml
- flash.each do |type, msg|
	= content_tag(:div, msg, class: "alert alert-#{type}")

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-static-top
	.container
		= link_to "Brand", root_url, class: "navbar-brand"

		%ul.nav.navbar-nav.navbar-right
			%li= link_to "About", about_url
			%li= link_to "Help", help_url
			- if logged_in?
				%li= link_to "#{current_user.name}", current_user
				%li= link_to "Users", users_url
				%li= link_to "Setting", edit_user_url(current_user)
				%li= link_to "Logout", logout_url, method: :delete
			- else
				%li= link_to "Sign Up", signup_url
				%li= link_to "Login", login_url

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title= full_title(yield :title)
		= csrf_meta_tags
		= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
	%body
		= render 'layouts/header'
		.container
			= render 'layouts/flash'
			= yield
			= debug params if Rails.env.development?